name: Git Actions Hackton - Fase 5 - CD - Push Region Docker Image 🚀

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  buildAndTest:
    name: Build Docker Image and Push to DockerHub
    runs-on: ubuntu-latest

    steps:

  #build:
   # needs: test
    #name: Build docker image
    #runs-on: ubuntu-latest

    #steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build image - 🐋
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Hackton.Consumer/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hackton-consumer:latest, ${{ secrets.DOCKERHUB_USERNAME }}/hackton-consumer:${{ github.run_number }}
